### ISSUE TITLE
[question] Additional options for page number positioning

### ISSUE THREAD

**Issue by kirk86** [David-Brewin/PowerpointToPDF#2]
Hi David,

thanks for this nice script, I was wondering if you could also add the following two options for page numbering positioning?

1. `TM = Top Middle`
2. `BM = Bottom Middle`

Thanks!

**Comment by David-Brewin** [comment]
Done as requested - except that I have used TC and BC (top/bottom centre) rather than TM and BM.

**Comment by kirk86** [comment]
Thanks David, you're a lifesaver!
